### ISSUE TITLE
Using -S with IRRs in different order yields different results

### ISSUE THREAD

**Issue by lucasalvatore** [bgp/bgpq4#37]
bgpq4 version: 0.0.6

Could you please clarify what the default behavior is when the `-S` flag is not used e.g what IRR is checked?  
Also, does the order of IRRs passed with `-S` matter?

I'm seeing weird behavior for a few AS-SETs.. example below using AS-GITHUB

No `-S`:
````
~ » bgpq4 -J -A -z AS-GITHUB                                                                                                                                       
policy-options {
replace:
  route-filter-list NN {
    route-filter 0.0.0.0/0 orlonger reject;
  }
}
````

Using RADB:
```
~ » bgpq4 -S RADB -J -A -z AS-GITHUB
policy-options {
replace:
  route-filter-list NN {
    route-filter 0.0.0.0/0 orlonger reject;
  }
}
```

Combining RIPE, RADB
```
~ » bgpq4 -S RIPE,RADB -J -A -z AS-GITHUB
policy-options {
replace:
  route-filter-list NN {
    140.82.112.0/20 exact;
    140.82.112.0/20 prefix-length-range /24-/24;
    143.55.64.0/20 exact;
    185.199.108.0/22 upto /24;
    192.30.252.0/22 upto /23;
  }
}
```
RADB,RIPE (reversed from previous example)
```
~ » bgpq4 -S RADB,RIPE -J -A -z AS-GITHUB
policy-options {
replace:
  route-filter-list NN {
    route-filter 0.0.0.0/0 orlonger reject;
  }
}
```
Just RIPE
```
~ » bgpq4 -S RIPE -J -A -z AS-GITHUB
policy-options {
replace:
  route-filter-list NN {
    185.199.108.0/22 upto /24;
  }
}
```

bgpq3 example:
```
~ » bgpq3 -J -A -z AS-GITHUB
policy-options {
replace:
  route-filter-list NN {
    140.82.112.0/20 exact;
    140.82.112.0/20 prefix-length-range /24-/24;
    143.55.64.0/20 exact;
    185.199.108.0/22 upto /24;
    192.30.252.0/22 upto /24;
  }
}
```

So is this behavior expected?  I feel like not passing `-S` should work but as shown it returns nothing.

**Comment by lukastribus** [comment]
Github has 3 as-set objects **with the same name** `AS-GITHUB` in different DB sources, one empty one is in RADB, and then there is one in ARIN and one in RIPE, both of the latter include AS36459.

Github in their PDB object, just refer to `AS-GITHUB` without mentioning a source.

So when RADB is tried first, then your result will be empty, because the as-set object in radb is actually empty (does not have `member: AS36459`).

    lukas@dev:~/bgpq4$ whois -h rr.ntt.net AS-GITHUB
    as-set:         AS-GITHUB
    descr:          GitHub Inc
    admin-c:        GITHUB-ABUSE
    tech-c:         GITHUB-NOC
    mnt-by:         MAINT-AS36459
    changed:        noc@github.com 20170628  #17:58:30Z
    source:         RADB
    
    as-set:         AS-GITHUB
    descr:          GitHub Inc
    admin-c:        GITHU-ARIN
    tech-c:         GITHU-ARIN
    members:        AS36459
    mbrs-by-ref:    MNT-GITHU
    notify:         noc@github.com
    mnt-by:         MNT-GITHU
    changed:        noc@github.com 20170503
    source:         ARIN
    
    as-set:         AS-GITHUB
    tech-c:         DUMY-RIPE
    admin-c:        DUMY-RIPE
    mnt-by:         us-github-1-mnt
    created:        2017-04-18T22:51:46Z
    last-modified:  2017-04-18T22:51:46Z
    source:         RIPE
    members:        AS36459
    descr:          GitHub
    org:            ORG-GI58-RIPE
    remarks:        ****************************
    remarks:        * THIS OBJECT IS MODIFIED
    remarks:        * Please note that all data that is generally regarded as personal
    remarks:        * data has been removed from this object.
    remarks:        * To view the original object, please query the RIPE Database at:
    remarks:        * http://www.ripe.net/whois
    remarks:        ****************************
    
    lukas@dev:~/bgpq4$
    


Suggestion: filter Github based on AS36459 instead of the inconsistent as-set or ask `noc@github.com` to make UNIQUE as-set or at least configure it correctly in RADB.


@job should `bgpq4` aggregate all sources instead? I don't think so.

**Comment by job** [comment]
This is not a bug in `bgpq4`, but rather Github must unify their IRR representation by making all objects equal in terms of members or outcome, or, delete redundant stale objects.

Additionally I strongly recommend that Github uses the "hierarchical" AS-SET notation, instead of "plain as-set names", this helps decrease the chance of a naming collision in the IRR set.

In this case I'd recommend renaming to `AS36459:AS-GITHUB` published in the `ARIN` database.

**Comment by lucasalvatore** [comment]
Thank you for the clarification guys.  i'll close this
