### ISSUE TITLE
Prefix's missing when using bgpq4 compared to bgpq3

### ISSUE THREAD

**Issue by MyGitUsrname** [bgp/bgpq4#79]
I've noticed that there are a few prefixes missing when running the AS-SET AS-VETTA against bgpq4 compared to bgpq3

~ ❯ bgpq3 -F "%n/%l\n" AS-VETTA | wc -l
     188
~ ❯ bgpq4 -F "%n/%l\n" AS-VETTA | wc -l
     174

I'm on MacOS 12.6.1, installed both via homebrew, both are the latest version.

~ ❯ bgpq4 -v
bgpq4 - a versatile utility to generate BGP filters
version: 1.7
website: https://github.com/bgp/bgpq4
maintainer: Job Snijders <job@sobornost.net>

~ ❯ bgpq3 -v
bgpq3: illegal option -- v
...
bgpq3 version: 0.1.36.1
Copyright(c) Alexandre Snarskii <snar@snar.spb.ru> 2007-2021

Let me know if you require any further info

**Comment by job** [comment]
Do you have an example of prefixes that are missing?

**Comment by MyGitUsrname** [comment]
These prefixes were recently added to the AS-SET, not showing when using bgpq4 but are when using bgpq3

103.51.100.0/23
103.51.100.0/24
103.51.101.0/24
103.232.226.0/23
103.232.226.0/24
103.232.227.0/24

**Comment by job** [comment]
I suspect the issue is that those IRR `route:` objects are invalid from an RPKI perspective, see https://irrexplorer.nlnog.net/prefix/103.51.100.0/23

`bgpq4` uses the `rr.ntt.net` IRR mirror service which applies the RPKI-based Origin Validation algorithm to IRR `route:` and `route6:` objects, whereas `bgpq3` uses `whois.radb.net` which does not apply RPKI-based filtering (unfortunately).

The results will become more similar if the RPKI ROA misconfigurations are rectified, or the erroneous IRR `route:` objects removed.

**Comment by MyGitUsrname** [comment]
Ah right, thanks for your help.
